
settings:
  jwt:
    secret: wecat
    timeout: 86400

  log:
    compress: 1
    consolestdout: 1
    filestdout: 1
    level: "debug"
    localtime: 1
    maxage: 30
    maxbackups: 300
    maxsize: 10240
    path: ./log/wecat.log
