
settings:
  application:
    domain: localhost:80
    host: 0.0.0.0
    ishttps: false
    port: 80
    readtimeout: 1
    writetimeout: 1

  jwt:
    secret: wecat
    timeout: 86400

  log:
    compress: 1
    consolestdout: 1
    filestdout: 1
    level: "debug"
    localtime: 1
    maxage: 30
    maxbackups: 300
    maxsize: 10240
    path: ./log/wecat.log
