
settings:
  application:
    domain: localhost:80
    host: 0.0.0.0
    ishttps: false
    port: "80"
    readtimeout: 1
    writetimeout: 1

  jwt:
    secret: wecat
    timeout: 86400

  log:
    compress: true
    consolestdout: true
    filestdout: true
    level: "debug"
    localtime: true
    maxage: 30
    maxbackups: 300
    maxsize: 10240
    path: ./log/wecat.log
  
  ssl:
    key: "/path/key.key"
    pem: "/path/pem.pem"
  
  redis:
    host: "127.0.0.1:6379"
    password: ""
    maxidle: 30
    maxactive: 30
    idletimeout: 200
