
Server:
  RunMode: debug
  HttpPort: 8000
  IsHttps: false
  ReadTimeout: 60
  WriteTimeout: 60
  SSL:
    key: "/path/key.key"
    pem: "/path/pem.pem"

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .yml

Database:
  BDType: mysql
  Username: root
  Passworld: z1x2c3@hutool
  Host: 172.16.106.131:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30

JWT:
  Secret: eddycjy
  Issuer: blog-service
  Expire: 7200

Email:
  Host: smtp.qq.com
  Post: 465
  UserName: xxxxxx@qq.com
  Password: xxxxxx
  IsSSL: true
  From: xxxxx@qq.com
  To:
    - xxxxxxxx@qq.com
    - xxxxxxxxxxxx@qq.com
  
Log:
  Compress: true
  consolestdout: true
  Filestdout: true
  Level: "debug"
  Localtime: true
  Maxage: 30
  Maxbackups: 300
  Maxsize: 10240
  Path: ./log/wecat.log

Redis:
  Host: "127.0.0.1:6379"
  Password: ""
  MaxIdle: 30
  MaxActive: 30
  IdleTimeout: 200
